### PR TITLE
WIP: [feature] Folder creation capability

### PR DESCRIPTION
**Pull request by tuancoltech**
Folder creation capability: https://github.com/ARK-Builders/ark-filepicker/issues/5

### CODE REVIEW

**Comment by mdrlzy** [comment]
We've actually moved FilePicker into [components](https://github.com/ARK-Builders/ark-components-android). Сan you create PR there?

**Comment by tuancoltech** [comment]
> We've actually moved FilePicker into [components](https://github.com/ARK-Builders/ark-components-android). Сan you create PR there?

@mdrlzy Sure. I'm just curious why we decided to move the `file-picker` module to `ark-components`?
BTW the new PR is here: https://github.com/ARK-Builders/ark-components-android/pull/41

**Comment by kirillt** [comment]
@tuancoltech this should result in better maintainability. The filepicker is almost always will be used with some other components. Also the components might depend on each other in the future.

**Comment by kirillt** [comment]
Substituted by https://github.com/ARK-Builders/ark-components-android/pull/41

**Pull request closed without merging**
